pub const PLAYER_MOVEMENT_SPEED: i32 = 2;
pub const BACKGROUND_WALLPAPER_MOVEMENT_SPEED: i32 = 1;
pub const SCREEN_HEIGHT: u32 = 600;
pub const SCREEN_WIDTH: u32 = 800;
pub const LOWER_NEG_SCREEN_WIDTH: i32 = -800;
pub const PERIODSLIMIT: u8 = 5;